/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _grup_12;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Furkan
 */
public class _Grup_12_update_KlnIletisim extends javax.swing.JFrame {

    
    DefaultTableModel model;
    _Grup_12_DbOperation dbOperation = new _Grup_12_DbOperation();
    int tblSatir = 0;
    public _Grup_12_update_KlnIletisim() {
        initComponents();
        model = (DefaultTableModel) tbl_iletisim.getModel();
        dbOperation.setArrayListIletims();
        ArrayList<_Grup_12_Iletisim> iletisims = dbOperation.iletisims;
        for(int i=0;i<iletisims.size();i++)
        {
            Object[] row = {
                iletisims.get(i).getId(),
                iletisims.get(i).getTelefon(),
                iletisims.get(i).getMail()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Mail = new javax.swing.JLabel();
        txt_Mail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_iletisim = new javax.swing.JTable();
        lbl_klnAdi = new javax.swing.JLabel();
        txt_searchIsim = new javax.swing.JTextField();
        btn_Guncelle = new javax.swing.JButton();
        btn_GeriDon = new javax.swing.JButton();
        lbl_Telefon = new javax.swing.JLabel();
        txt_Telefon = new javax.swing.JTextField();
        btn_sec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Mail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Mail.setText("Mail:");

        tbl_iletisim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Telefon", "Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_iletisim);

        lbl_klnAdi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_klnAdi.setText("Arama Kutusu:");

        txt_searchIsim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_searchIsim.setText("Ara");
        txt_searchIsim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchIsimMouseClicked(evt);
            }
        });
        txt_searchIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchIsimActionPerformed(evt);
            }
        });
        txt_searchIsim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchIsimKeyReleased(evt);
            }
        });

        btn_Guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        btn_GeriDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_GeriDon.setText("Geri Dön");
        btn_GeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeriDonActionPerformed(evt);
            }
        });

        lbl_Telefon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Telefon.setText("Telefon:");

        btn_sec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sec.setText("Seç");
        btn_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_klnAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_searchIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sec))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Mail, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(txt_Telefon))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_GeriDon)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_klnAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_searchIsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sec))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Telefon)
                    .addComponent(txt_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Mail)
                    .addComponent(txt_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_GeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchIsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchIsimActionPerformed

    private void btn_GeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeriDonActionPerformed
        _Grup_12_KullaniciIslemleri kullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
        kullaniciIslemleri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_GeriDonActionPerformed

    private void txt_searchIsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchIsimMouseClicked
        txt_searchIsim.setText("");
    }//GEN-LAST:event_txt_searchIsimMouseClicked

    private void txt_searchIsimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchIsimKeyReleased
        String searchKey = txt_searchIsim.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
        tbl_iletisim.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txt_searchIsimKeyReleased

    private void btn_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secActionPerformed
        tblSatir = tbl_iletisim.getSelectedRow();
        if(tblSatir != -1)
        {
            String telefon = (String) model.getValueAt(tblSatir,1);
            String mail = (String) model.getValueAt(tblSatir,2);
            
            txt_Telefon.setText(telefon);
            txt_Mail.setText(mail);
        }

    }//GEN-LAST:event_btn_secActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        tblSatir = tbl_iletisim.getSelectedRow();
        if(tblSatir != -1)
        {
            int ID = (int) model.getValueAt(tblSatir, 0);
            dbOperation.updateIletisim(ID, txt_Telefon.getText(), txt_Mail.getText());
            JOptionPane.showMessageDialog(null, "İletişim bilgisi güncelleme işlemi başarılı");
            _Grup_12_KullaniciIslemleri grup_12_KullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
            grup_12_KullaniciIslemleri.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnIletisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnIletisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnIletisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnIletisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_update_KlnIletisim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GeriDon;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_sec;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Mail;
    private javax.swing.JLabel lbl_Telefon;
    private javax.swing.JLabel lbl_klnAdi;
    private javax.swing.JTable tbl_iletisim;
    private javax.swing.JTextField txt_Mail;
    private javax.swing.JTextField txt_Telefon;
    private javax.swing.JTextField txt_searchIsim;
    // End of variables declaration//GEN-END:variables
}
