/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _grup_12;

/**
 *
 * @author Furkan
 */
public class _Grup_12_KullaniciIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form _Grup_12_KullaniciListesi
     */
    public _Grup_12_KullaniciIslemleri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_update_klnIletisim = new javax.swing.JButton();
        btn_update_klnArac = new javax.swing.JButton();
        btn_delete_kln = new javax.swing.JButton();
        btn_geriDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_update_klnIletisim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update_klnIletisim.setText("Kullanıcı İletişim Bilgisi Güncelle");
        btn_update_klnIletisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_klnIletisimActionPerformed(evt);
            }
        });

        btn_update_klnArac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update_klnArac.setText("Kullanıcı Araç Bilgisi Güncelle");
        btn_update_klnArac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_klnAracActionPerformed(evt);
            }
        });

        btn_delete_kln.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete_kln.setText("Kullanıcı Silme");
        btn_delete_kln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_klnActionPerformed(evt);
            }
        });

        btn_geriDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_geriDon.setText("Geri Dön");
        btn_geriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_geriDon)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update_klnIletisim, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_klnArac, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_kln, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btn_update_klnIletisim, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update_klnArac, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete_kln, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_geriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_update_klnIletisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_klnIletisimActionPerformed
        _Grup_12_update_KlnIletisim klnIletisim = new _Grup_12_update_KlnIletisim();
        klnIletisim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_update_klnIletisimActionPerformed

    private void btn_update_klnAracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_klnAracActionPerformed
        _Grup_12_update_KlnArac klnArac = new _Grup_12_update_KlnArac();
        klnArac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_update_klnAracActionPerformed

    private void btn_delete_klnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_klnActionPerformed
        _Grup_12_delete_Kln kln_delete = new _Grup_12_delete_Kln();
        kln_delete.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_delete_klnActionPerformed

    private void btn_geriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriDonActionPerformed
        _Grup_12_AnaSayfa anaSayfa = new _Grup_12_AnaSayfa();
        anaSayfa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_geriDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_KullaniciIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_kln;
    private javax.swing.JButton btn_geriDon;
    private javax.swing.JButton btn_update_klnArac;
    private javax.swing.JButton btn_update_klnIletisim;
    // End of variables declaration//GEN-END:variables
}
