/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _grup_12;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Furkan
 */
public class _Grup_12_delete_Kln extends javax.swing.JFrame {

    DefaultTableModel model;
    _Grup_12_DbOperation dbOperation = new _Grup_12_DbOperation();
    int tblSatir = 0;
    public _Grup_12_delete_Kln() {
        initComponents();
        model = (DefaultTableModel) tbl_Kln.getModel();
        dbOperation.setArrayListUsers();
        ArrayList<_Grup_12_User> users = dbOperation.users;
        for(int i=0;i<users.size();i++)
        {
            Object[] row = {
                users.get(i).getId(),
                users.get(i).getIsim(),
                users.get(i).getSoyIsim(),
                users.get(i).getTc()  
            };
            model.addRow(row);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_klnAdi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Kln = new javax.swing.JTable();
        txt_searchIsim = new javax.swing.JTextField();
        btn_Sil = new javax.swing.JButton();
        btn_GeriDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_klnAdi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_klnAdi.setText("Arama Kutusu:");

        tbl_Kln.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "İsim", "Soy İsim", "Tc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Kln);
        if (tbl_Kln.getColumnModel().getColumnCount() > 0) {
            tbl_Kln.getColumnModel().getColumn(0).setResizable(false);
            tbl_Kln.getColumnModel().getColumn(1).setResizable(false);
            tbl_Kln.getColumnModel().getColumn(2).setResizable(false);
            tbl_Kln.getColumnModel().getColumn(3).setResizable(false);
        }

        txt_searchIsim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_searchIsim.setText("Ara");
        txt_searchIsim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchIsimMouseClicked(evt);
            }
        });
        txt_searchIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchIsimActionPerformed(evt);
            }
        });
        txt_searchIsim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchIsimKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchIsimKeyTyped(evt);
            }
        });

        btn_Sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });

        btn_GeriDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_GeriDon.setText("Geri Dön");
        btn_GeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbl_klnAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_GeriDon)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_searchIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(150, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_klnAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_searchIsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_GeriDon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeriDonActionPerformed
        _Grup_12_KullaniciIslemleri kullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
        kullaniciIslemleri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_GeriDonActionPerformed

    private void txt_searchIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchIsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchIsimActionPerformed

    private void txt_searchIsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchIsimMouseClicked
        txt_searchIsim.setText("");
    }//GEN-LAST:event_txt_searchIsimMouseClicked

    private void txt_searchIsimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchIsimKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchIsimKeyTyped

    private void txt_searchIsimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchIsimKeyReleased
        String searchKey = txt_searchIsim.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
        tbl_Kln.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txt_searchIsimKeyReleased

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
        tblSatir = tbl_Kln.getSelectedRow();
        if(tblSatir != -1)
        {
            int a = (int) model.getValueAt(tblSatir,0);
            dbOperation.deleteUser(dbOperation.search_kln_iletisim_arac_klnID(a));
            JOptionPane.showMessageDialog(null, "Kullanıcı silme işlemi başarılı");
            _Grup_12_KullaniciIslemleri grup_12_KullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
            grup_12_KullaniciIslemleri.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_SilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_delete_Kln.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_delete_Kln.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_delete_Kln.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_delete_Kln.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_delete_Kln().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GeriDon;
    private javax.swing.JButton btn_Sil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_klnAdi;
    private javax.swing.JTable tbl_Kln;
    private javax.swing.JTextField txt_searchIsim;
    // End of variables declaration//GEN-END:variables
}
