/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _grup_12;

import javax.swing.JOptionPane;

/**
 *
 * @author Furkan
 */
public class _Grup_12_KullaniciKayit extends javax.swing.JFrame {

    _Grup_12_DbOperation dbOperation = new _Grup_12_DbOperation();
    _Grup_12_InterfaceOperations interfaceOperations = new _Grup_12_InterfaceOperations();
    public _Grup_12_KullaniciKayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Isim = new javax.swing.JTextField();
        txt_SoyIsim = new javax.swing.JTextField();
        txt_TC = new javax.swing.JTextField();
        txt_Telefon = new javax.swing.JTextField();
        txt_Mail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Plaka = new javax.swing.JTextField();
        txt_Marka = new javax.swing.JTextField();
        txt_Model = new javax.swing.JTextField();
        txt_Renk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_KayıtYap = new javax.swing.JButton();
        btn_GeriDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("İsim:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soy İsim:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TC:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefon:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kullanıcı Bilgileri");

        txt_Isim.setText("İsim");
        txt_Isim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_IsimMouseClicked(evt);
            }
        });

        txt_SoyIsim.setText("Soy İsim");
        txt_SoyIsim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_SoyIsimMouseClicked(evt);
            }
        });
        txt_SoyIsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoyIsimActionPerformed(evt);
            }
        });

        txt_TC.setText("TC");
        txt_TC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TCMouseClicked(evt);
            }
        });
        txt_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TCActionPerformed(evt);
            }
        });

        txt_Telefon.setText("Telefon");
        txt_Telefon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TelefonMouseClicked(evt);
            }
        });

        txt_Mail.setText("Mail");
        txt_Mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_MailMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mail:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Araç Bilgileri");

        txt_Plaka.setText("Plaka");
        txt_Plaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PlakaMouseClicked(evt);
            }
        });

        txt_Marka.setText("Marka");
        txt_Marka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_MarkaMouseClicked(evt);
            }
        });
        txt_Marka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MarkaActionPerformed(evt);
            }
        });

        txt_Model.setText("Model");
        txt_Model.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ModelMouseClicked(evt);
            }
        });
        txt_Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ModelActionPerformed(evt);
            }
        });

        txt_Renk.setText("Renk");
        txt_Renk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_RenkMouseClicked(evt);
            }
        });
        txt_Renk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RenkActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Plaka:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Marka:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Model:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Renk:");

        btn_KayıtYap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_KayıtYap.setText("Kayıt Yap");
        btn_KayıtYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KayıtYapActionPerformed(evt);
            }
        });

        btn_GeriDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_GeriDon.setText("Geri Dön");
        btn_GeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_KayıtYap)
                .addGap(18, 18, 18)
                .addComponent(btn_GeriDon)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_Telefon)
                                .addComponent(txt_TC)
                                .addComponent(txt_SoyIsim)
                                .addComponent(txt_Isim))
                            .addComponent(txt_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Plaka)
                            .addComponent(txt_Marka, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txt_Model)
                            .addComponent(txt_Renk)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_Plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Renk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_SoyIsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_TC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_KayıtYap)
                    .addComponent(btn_GeriDon))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SoyIsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoyIsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoyIsimActionPerformed

    private void txt_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TCActionPerformed

    private void txt_MarkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MarkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MarkaActionPerformed

    private void txt_ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ModelActionPerformed

    private void txt_RenkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RenkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RenkActionPerformed

    private void btn_GeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeriDonActionPerformed
        _Grup_12_AnaSayfa anaSayfa = new _Grup_12_AnaSayfa();
        anaSayfa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_GeriDonActionPerformed

    private void txt_IsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_IsimMouseClicked
        if(txt_Isim.getText().equals("İsim"))
        {
           txt_Isim.setText(""); 
        }
    }//GEN-LAST:event_txt_IsimMouseClicked

    private void txt_SoyIsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_SoyIsimMouseClicked
        if(txt_SoyIsim.getText().equals("Soy İsim"))
        {
           txt_SoyIsim.setText(""); 
        }
    }//GEN-LAST:event_txt_SoyIsimMouseClicked

    private void txt_TCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TCMouseClicked
        if(txt_TC.getText().equals("TC"))
        {
           txt_TC.setText(""); 
        }
    }//GEN-LAST:event_txt_TCMouseClicked

    private void txt_TelefonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TelefonMouseClicked
        if(txt_Telefon.getText().equals("Telefon"))
        {
           txt_Telefon.setText(""); 
        }
    }//GEN-LAST:event_txt_TelefonMouseClicked

    private void txt_MailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MailMouseClicked
        if(txt_Mail.getText().equals("Mail"))
        {
           txt_Mail.setText(""); 
        }
    }//GEN-LAST:event_txt_MailMouseClicked

    private void txt_PlakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PlakaMouseClicked
        if(txt_Plaka.getText().equals("Plaka"))
        {
           txt_Plaka.setText(""); 
        }
    }//GEN-LAST:event_txt_PlakaMouseClicked

    private void txt_MarkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MarkaMouseClicked
        if(txt_Marka.getText().equals("Marka"))
        {
           txt_Marka.setText(""); 
        }
    }//GEN-LAST:event_txt_MarkaMouseClicked

    private void txt_ModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ModelMouseClicked
        if(txt_Model.getText().equals("Model"))
        {
           txt_Model.setText(""); 
        }
    }//GEN-LAST:event_txt_ModelMouseClicked

    private void txt_RenkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_RenkMouseClicked
        if(txt_Renk.getText().equals("Renk"))
        {
           txt_Renk.setText(""); 
        }
    }//GEN-LAST:event_txt_RenkMouseClicked

    private void btn_KayıtYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KayıtYapActionPerformed
        if(interfaceOperations.kullaniciKaydiKontrol(
                interfaceOperations.isNameAndSurname(txt_Isim.getText()),
                interfaceOperations.isNameAndSurname(txt_SoyIsim.getText()),
                interfaceOperations.isTC(txt_TC.getText()),
                interfaceOperations.isTelefon(txt_Telefon.getText()),
                interfaceOperations.isEmail(txt_Mail.getText())
                ) == true )
        {
            dbOperation.insert_kullanici(
                txt_Isim.getText(),
                txt_SoyIsim.getText(),
                txt_TC.getText(),
                txt_Telefon.getText(),
                txt_Mail.getText(),
                txt_Marka.getText(),
                txt_Renk.getText(), 
                txt_Model.getText(), 
                txt_Plaka.getText());
        JOptionPane.showMessageDialog(null, "Kullanıcı kaydı başarılı");
        _Grup_12_AnaSayfa anaSayfa = new _Grup_12_AnaSayfa();
        anaSayfa.setVisible(true);
        this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Yanlış bilgi girdiniz!");
        }
        
    }//GEN-LAST:event_btn_KayıtYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_KullaniciKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_KullaniciKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GeriDon;
    private javax.swing.JButton btn_KayıtYap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Isim;
    private javax.swing.JTextField txt_Mail;
    private javax.swing.JTextField txt_Marka;
    private javax.swing.JTextField txt_Model;
    private javax.swing.JTextField txt_Plaka;
    private javax.swing.JTextField txt_Renk;
    private javax.swing.JTextField txt_SoyIsim;
    private javax.swing.JTextField txt_TC;
    private javax.swing.JTextField txt_Telefon;
    // End of variables declaration//GEN-END:variables
}
