/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _grup_12;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JToggleButton;


public class _Grup_12_F_Otopark extends javax.swing.JFrame {

    _Grup_12_DbOperation dbOperation = new _Grup_12_DbOperation();
    ArrayList<JToggleButton> jToggleButtons = new ArrayList<JToggleButton>();
    public _Grup_12_F_Otopark() {
        initComponents();
        dbOperation.setArrayListOtopark();
        setArrayListJToggleButton();
        setTbtnOtopark();
        jToggleButton();
        
    }
    public void jToggleButton ()
    {
        for(int i = 0; i<jToggleButtons.size();i++)
        {
            if(jToggleButtons.get(i).isSelected() == true)
        {
            jToggleButtons.get(i).setBackground(Color.red);
        }
            else
            {
            jToggleButtons.get(i).setBackground(Color.green);   
            }
        }    
    }
    public void setArrayListJToggleButton()
    {
        jToggleButtons.add(tBtn_No1_1);
        jToggleButtons.add(tBtn_No1_2);
        jToggleButtons.add(tBtn_No1_3);
        jToggleButtons.add(tBtn_No1_4);
        jToggleButtons.add(tBtn_No1_5);
        jToggleButtons.add(tBtn_No1_6);
        jToggleButtons.add(tBtn_No1_7);
        jToggleButtons.add(tBtn_No1_8);
        jToggleButtons.add(tBtn_No2_1);
        jToggleButtons.add(tBtn_No2_2);
        jToggleButtons.add(tBtn_No2_3);
        jToggleButtons.add(tBtn_No2_4);
        jToggleButtons.add(tBtn_No2_5);
        jToggleButtons.add(tBtn_No2_6);
        jToggleButtons.add(tBtn_No2_7);
        jToggleButtons.add(tBtn_No2_8);
        jToggleButtons.add(tBtn_No3_1);
        jToggleButtons.add(tBtn_No3_2);
        jToggleButtons.add(tBtn_No3_3);
        jToggleButtons.add(tBtn_No3_4);
        jToggleButtons.add(tBtn_No3_5);
        jToggleButtons.add(tBtn_No3_6);
        jToggleButtons.add(tBtn_No3_7);
        jToggleButtons.add(tBtn_No3_8);
        
    }
    public void setTbtnOtopark()
    {
        int size = dbOperation.otopark.size();
        for(int i=0; i < size ;i++)
        {
            jToggleButtons.get(i).setSelected(dbOperation.otopark.get(i).otoparkDoluluk);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Kat1 = new javax.swing.JLabel();
        tBtn_No1_1 = new javax.swing.JToggleButton();
        tBtn_No1_2 = new javax.swing.JToggleButton();
        tBtn_No1_3 = new javax.swing.JToggleButton();
        tBtn_No1_4 = new javax.swing.JToggleButton();
        tBtn_No1_5 = new javax.swing.JToggleButton();
        tBtn_No1_6 = new javax.swing.JToggleButton();
        tBtn_No1_7 = new javax.swing.JToggleButton();
        tBtn_No1_8 = new javax.swing.JToggleButton();
        tBtn_No2_1 = new javax.swing.JToggleButton();
        tBtn_No2_2 = new javax.swing.JToggleButton();
        tBtn_No2_3 = new javax.swing.JToggleButton();
        lbl_Kat2 = new javax.swing.JLabel();
        tBtn_No2_4 = new javax.swing.JToggleButton();
        tBtn_No2_5 = new javax.swing.JToggleButton();
        tBtn_No2_6 = new javax.swing.JToggleButton();
        tBtn_No2_7 = new javax.swing.JToggleButton();
        tBtn_No2_8 = new javax.swing.JToggleButton();
        tBtn_No3_8 = new javax.swing.JToggleButton();
        tBtn_No3_5 = new javax.swing.JToggleButton();
        tBtn_No3_2 = new javax.swing.JToggleButton();
        tBtn_No3_6 = new javax.swing.JToggleButton();
        tBtn_No3_3 = new javax.swing.JToggleButton();
        lbl_Kat3 = new javax.swing.JLabel();
        tBtn_No3_4 = new javax.swing.JToggleButton();
        tBtn_No3_7 = new javax.swing.JToggleButton();
        tBtn_No3_1 = new javax.swing.JToggleButton();
        btn_geriDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Kat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Kat1.setText("1.Kat");

        tBtn_No1_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_1.setText("1 Numara");
        tBtn_No1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_1ActionPerformed(evt);
            }
        });

        tBtn_No1_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_2.setText("2 Numara");
        tBtn_No1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_2ActionPerformed(evt);
            }
        });

        tBtn_No1_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_3.setText("3 Numara");
        tBtn_No1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_3ActionPerformed(evt);
            }
        });

        tBtn_No1_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_4.setText("4 Numara");
        tBtn_No1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_4ActionPerformed(evt);
            }
        });

        tBtn_No1_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_5.setText("5 Numara");
        tBtn_No1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_5ActionPerformed(evt);
            }
        });

        tBtn_No1_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_6.setText("6 Numara");
        tBtn_No1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_6ActionPerformed(evt);
            }
        });

        tBtn_No1_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_7.setText("7 Numara");
        tBtn_No1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_7ActionPerformed(evt);
            }
        });

        tBtn_No1_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No1_8.setText("8 Numara");
        tBtn_No1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No1_8ActionPerformed(evt);
            }
        });

        tBtn_No2_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_1.setText("1 Numara");
        tBtn_No2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_1ActionPerformed(evt);
            }
        });

        tBtn_No2_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_2.setText("2 Numara");
        tBtn_No2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_2ActionPerformed(evt);
            }
        });

        tBtn_No2_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_3.setText("3 Numara");
        tBtn_No2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_3ActionPerformed(evt);
            }
        });

        lbl_Kat2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Kat2.setText("2.Kat");

        tBtn_No2_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_4.setText("4 Numara");
        tBtn_No2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_4ActionPerformed(evt);
            }
        });

        tBtn_No2_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_5.setText("5 Numara");
        tBtn_No2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_5ActionPerformed(evt);
            }
        });

        tBtn_No2_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_6.setText("6 Numara");
        tBtn_No2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_6ActionPerformed(evt);
            }
        });

        tBtn_No2_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_7.setText("7 Numara");
        tBtn_No2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_7ActionPerformed(evt);
            }
        });

        tBtn_No2_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No2_8.setText("8 Numara");
        tBtn_No2_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No2_8ActionPerformed(evt);
            }
        });

        tBtn_No3_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_8.setText("8 Numara");
        tBtn_No3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_8ActionPerformed(evt);
            }
        });

        tBtn_No3_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_5.setText("5 Numara");
        tBtn_No3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_5ActionPerformed(evt);
            }
        });

        tBtn_No3_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_2.setText("2 Numara");
        tBtn_No3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_2ActionPerformed(evt);
            }
        });

        tBtn_No3_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_6.setText("6 Numara");
        tBtn_No3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_6ActionPerformed(evt);
            }
        });

        tBtn_No3_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_3.setText("3 Numara");
        tBtn_No3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_3ActionPerformed(evt);
            }
        });

        lbl_Kat3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Kat3.setText("3.Kat");

        tBtn_No3_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_4.setText("4 Numara");
        tBtn_No3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_4ActionPerformed(evt);
            }
        });

        tBtn_No3_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_7.setText("7 Numara");
        tBtn_No3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_7ActionPerformed(evt);
            }
        });

        tBtn_No3_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tBtn_No3_1.setText("1 Numara");
        tBtn_No3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtn_No3_1ActionPerformed(evt);
            }
        });

        btn_geriDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_geriDon.setText("Geri Dön");
        btn_geriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Kat1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Kat2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Kat3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tBtn_No1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tBtn_No1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tBtn_No2_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tBtn_No2_2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(tBtn_No3_2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(tBtn_No3_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tBtn_No1_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No1_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No1_7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tBtn_No1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No1_8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tBtn_No2_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No2_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No2_7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tBtn_No2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No2_8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tBtn_No3_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No3_8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tBtn_No3_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No3_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtn_No3_7)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_geriDon)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_No1_1)
                            .addComponent(tBtn_No1_3)
                            .addComponent(tBtn_No1_5)
                            .addComponent(tBtn_No1_7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_No1_2)
                            .addComponent(tBtn_No1_4)
                            .addComponent(tBtn_No1_6)
                            .addComponent(tBtn_No1_8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_Kat1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_No2_1)
                            .addComponent(tBtn_No2_3)
                            .addComponent(tBtn_No2_5)
                            .addComponent(tBtn_No2_7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_No2_2)
                            .addComponent(tBtn_No2_4)
                            .addComponent(tBtn_No2_6)
                            .addComponent(tBtn_No2_8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_Kat2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_No3_1)
                            .addComponent(tBtn_No3_3)
                            .addComponent(tBtn_No3_5)
                            .addComponent(tBtn_No3_7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn_No3_2)
                            .addComponent(tBtn_No3_4)
                            .addComponent(tBtn_No3_6)
                            .addComponent(tBtn_No3_8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_Kat3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btn_geriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tBtn_No1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_1ActionPerformed
        
        
    }//GEN-LAST:event_tBtn_No1_1ActionPerformed

    private void tBtn_No1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_2ActionPerformed

    private void tBtn_No1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_3ActionPerformed

    private void tBtn_No1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_4ActionPerformed

    private void tBtn_No1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_5ActionPerformed

    private void tBtn_No1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_6ActionPerformed

    private void tBtn_No1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_7ActionPerformed

    private void tBtn_No1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No1_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No1_8ActionPerformed

    private void tBtn_No2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_1ActionPerformed

    private void tBtn_No2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_2ActionPerformed

    private void tBtn_No2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_3ActionPerformed

    private void tBtn_No2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_4ActionPerformed

    private void tBtn_No2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_5ActionPerformed

    private void tBtn_No2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_6ActionPerformed

    private void tBtn_No2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_7ActionPerformed

    private void tBtn_No2_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No2_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No2_8ActionPerformed

    private void tBtn_No3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_8ActionPerformed

    private void tBtn_No3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_5ActionPerformed

    private void tBtn_No3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_2ActionPerformed

    private void tBtn_No3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_6ActionPerformed

    private void tBtn_No3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_3ActionPerformed

    private void tBtn_No3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_4ActionPerformed

    private void tBtn_No3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_7ActionPerformed

    private void tBtn_No3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtn_No3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtn_No3_1ActionPerformed

    private void btn_geriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriDonActionPerformed
        _Grup_12_AnaSayfa anaSayfa = new _Grup_12_AnaSayfa();
        anaSayfa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_geriDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_F_Otopark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_F_Otopark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_F_Otopark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_F_Otopark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_F_Otopark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geriDon;
    private javax.swing.JLabel lbl_Kat1;
    private javax.swing.JLabel lbl_Kat2;
    private javax.swing.JLabel lbl_Kat3;
    private javax.swing.JToggleButton tBtn_No1_1;
    private javax.swing.JToggleButton tBtn_No1_2;
    private javax.swing.JToggleButton tBtn_No1_3;
    private javax.swing.JToggleButton tBtn_No1_4;
    private javax.swing.JToggleButton tBtn_No1_5;
    private javax.swing.JToggleButton tBtn_No1_6;
    private javax.swing.JToggleButton tBtn_No1_7;
    private javax.swing.JToggleButton tBtn_No1_8;
    private javax.swing.JToggleButton tBtn_No2_1;
    private javax.swing.JToggleButton tBtn_No2_2;
    private javax.swing.JToggleButton tBtn_No2_3;
    private javax.swing.JToggleButton tBtn_No2_4;
    private javax.swing.JToggleButton tBtn_No2_5;
    private javax.swing.JToggleButton tBtn_No2_6;
    private javax.swing.JToggleButton tBtn_No2_7;
    private javax.swing.JToggleButton tBtn_No2_8;
    private javax.swing.JToggleButton tBtn_No3_1;
    private javax.swing.JToggleButton tBtn_No3_2;
    private javax.swing.JToggleButton tBtn_No3_3;
    private javax.swing.JToggleButton tBtn_No3_4;
    private javax.swing.JToggleButton tBtn_No3_5;
    private javax.swing.JToggleButton tBtn_No3_6;
    private javax.swing.JToggleButton tBtn_No3_7;
    private javax.swing.JToggleButton tBtn_No3_8;
    // End of variables declaration//GEN-END:variables
}
