/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _grup_12;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Furkan
 */
public class _Grup_12_update_KlnArac extends javax.swing.JFrame {

    DefaultTableModel model;
    _Grup_12_DbOperation dbOperation = new _Grup_12_DbOperation();
    int tblSatir = 0;
    public _Grup_12_update_KlnArac() {
        initComponents();
        model = (DefaultTableModel) tbl_Arac.getModel();
        dbOperation.setArrayListCars();
        ArrayList<_Grup_12_Arac> cars = dbOperation.cars;
        for(int i=0;i<cars.size();i++)
        {
            Object[] row = {
                cars.get(i).getId(),
                cars.get(i).getMarka(),
                cars.get(i).getModel(),
                cars.get(i).getRenk(),
                cars.get(i).getPlaka()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Arac = new javax.swing.JTable();
        lbl_plaka = new javax.swing.JLabel();
        txt_searchPlaka = new javax.swing.JTextField();
        btn_GeriDon = new javax.swing.JButton();
        lbl_Marka = new javax.swing.JLabel();
        txt_Marka = new javax.swing.JTextField();
        lbl_Renk = new javax.swing.JLabel();
        txt_Renk = new javax.swing.JTextField();
        txt_Model = new javax.swing.JTextField();
        lbl_Model = new javax.swing.JLabel();
        lbl_Plaka = new javax.swing.JLabel();
        txt_Plaka = new javax.swing.JTextField();
        btn_Guncelle = new javax.swing.JButton();
        btn_sec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Arac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marka", "Model", "Renk", "Plaka"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Arac);
        if (tbl_Arac.getColumnModel().getColumnCount() > 0) {
            tbl_Arac.getColumnModel().getColumn(0).setResizable(false);
            tbl_Arac.getColumnModel().getColumn(1).setResizable(false);
            tbl_Arac.getColumnModel().getColumn(2).setResizable(false);
            tbl_Arac.getColumnModel().getColumn(3).setResizable(false);
            tbl_Arac.getColumnModel().getColumn(4).setResizable(false);
        }

        lbl_plaka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_plaka.setText("Arama Kutusu:");

        txt_searchPlaka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_searchPlaka.setText("Ara");
        txt_searchPlaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchPlakaMouseClicked(evt);
            }
        });
        txt_searchPlaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchPlakaActionPerformed(evt);
            }
        });
        txt_searchPlaka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchPlakaKeyReleased(evt);
            }
        });

        btn_GeriDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_GeriDon.setText("Geri Dön");
        btn_GeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeriDonActionPerformed(evt);
            }
        });

        lbl_Marka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Marka.setText("Marka:");

        lbl_Renk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Renk.setText("Renk:");

        lbl_Model.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Model.setText("Model:");

        lbl_Plaka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Plaka.setText("Plaka:");

        btn_Guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        btn_sec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sec.setText("Seç");
        btn_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_searchPlaka, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sec)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btn_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_GeriDon)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Model, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Marka)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_Marka, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txt_Model))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Renk, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Renk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_searchPlaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sec))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Marka)
                    .addComponent(txt_Marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Renk)
                    .addComponent(txt_Renk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Model)
                    .addComponent(txt_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Plaka)
                    .addComponent(txt_Plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_GeriDon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeriDonActionPerformed
        _Grup_12_KullaniciIslemleri kullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
        kullaniciIslemleri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_GeriDonActionPerformed

    private void txt_searchPlakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchPlakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchPlakaActionPerformed

    private void txt_searchPlakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchPlakaMouseClicked
        txt_searchPlaka.setText("");
    }//GEN-LAST:event_txt_searchPlakaMouseClicked

    private void txt_searchPlakaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchPlakaKeyReleased
        String searchKey = txt_searchPlaka.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
        tbl_Arac.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_txt_searchPlakaKeyReleased

    private void btn_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secActionPerformed
        tblSatir = tbl_Arac.getSelectedRow();
        if(tblSatir != -1)
        {
            String marka = (String) model.getValueAt(tblSatir,1);
            String arac_model = (String) model.getValueAt(tblSatir,2);
            String renk = (String) model.getValueAt(tblSatir,3);
            String plaka = (String) model.getValueAt(tblSatir,4);
            txt_Marka.setText(marka);
            txt_Model.setText(arac_model);
            txt_Renk.setText(renk);
            txt_Plaka.setText(plaka);
        }
        
    }//GEN-LAST:event_btn_secActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        tblSatir = tbl_Arac.getSelectedRow();
        if(tblSatir != -1)
        {
            int ID = (int) model.getValueAt(tblSatir, 0);
            dbOperation.updateArac(ID, txt_Marka.getText(), txt_Model.getText(), txt_Renk.getText(), txt_Plaka.getText());
            JOptionPane.showMessageDialog(null, "Araç bilgisi güncelleme işlemi başarılı");
            _Grup_12_KullaniciIslemleri grup_12_KullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
            grup_12_KullaniciIslemleri.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnArac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnArac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnArac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_update_KlnArac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_update_KlnArac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GeriDon;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_sec;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Marka;
    private javax.swing.JLabel lbl_Model;
    private javax.swing.JLabel lbl_Plaka;
    private javax.swing.JLabel lbl_Renk;
    private javax.swing.JLabel lbl_plaka;
    private javax.swing.JTable tbl_Arac;
    private javax.swing.JTextField txt_Marka;
    private javax.swing.JTextField txt_Model;
    private javax.swing.JTextField txt_Plaka;
    private javax.swing.JTextField txt_Renk;
    private javax.swing.JTextField txt_searchPlaka;
    // End of variables declaration//GEN-END:variables
}
