package _grup_12;

/**
 *
 * @author Furkan
 */
public class _Grup_12_AnaSayfa extends javax.swing.JFrame {

    //String adminIsim;
    public _Grup_12_AnaSayfa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_KullaniciKaydi = new javax.swing.JButton();
        btn_KullaniciIslemleri = new javax.swing.JButton();
        btn_OtoparkBilgisi = new javax.swing.JButton();
        btn_AracGiris = new javax.swing.JButton();
        btn_AracCikis = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_KullaniciKaydi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_KullaniciKaydi.setText("Kullanıcı Kaydı");
        btn_KullaniciKaydi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KullaniciKaydiActionPerformed(evt);
            }
        });

        btn_KullaniciIslemleri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_KullaniciIslemleri.setText("Kullanıcı İşlemleri");
        btn_KullaniciIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KullaniciIslemleriActionPerformed(evt);
            }
        });

        btn_OtoparkBilgisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_OtoparkBilgisi.setText("Otopark Bilgisi");
        btn_OtoparkBilgisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OtoparkBilgisiActionPerformed(evt);
            }
        });

        btn_AracGiris.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_AracGiris.setText("Araç Giriş");
        btn_AracGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AracGirisActionPerformed(evt);
            }
        });

        btn_AracCikis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_AracCikis.setText("Araç Çıkış");
        btn_AracCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AracCikisActionPerformed(evt);
            }
        });

        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Exit.setText("Çıkış Yap");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_AracCikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_KullaniciKaydi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btn_OtoparkBilgisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_KullaniciIslemleri)
                            .addComponent(btn_AracGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_KullaniciKaydi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_KullaniciIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_OtoparkBilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_AracGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btn_AracCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KullaniciKaydiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KullaniciKaydiActionPerformed
        _Grup_12_KullaniciKayit kullaniciKayit = new _Grup_12_KullaniciKayit();
        kullaniciKayit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_KullaniciKaydiActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_OtoparkBilgisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OtoparkBilgisiActionPerformed
        _Grup_12_F_Otopark fOtopark = new _Grup_12_F_Otopark();
        fOtopark.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_OtoparkBilgisiActionPerformed

    private void btn_AracGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AracGirisActionPerformed
        _Grup_12_AracGiris aracGirisi = new _Grup_12_AracGiris();
        aracGirisi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_AracGirisActionPerformed

    private void btn_AracCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AracCikisActionPerformed
        _Grup_12_AracCikis aracCikisi = new _Grup_12_AracCikis();
        aracCikisi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_AracCikisActionPerformed

    private void btn_KullaniciIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KullaniciIslemleriActionPerformed
        _Grup_12_KullaniciIslemleri kullaniciIslemleri = new _Grup_12_KullaniciIslemleri();
        kullaniciIslemleri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_KullaniciIslemleriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_12_AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_12_AnaSayfa().setVisible(true);
            }
        });
    }
    //public void setAdminIsim(String dbIsim)
    //{
        //adminIsim = dbIsim;
        //isim= dbIsim;
        //lbl_Merhaba.setText("Merhaba "+adminIsim);
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AracCikis;
    private javax.swing.JButton btn_AracGiris;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_KullaniciIslemleri;
    private javax.swing.JButton btn_KullaniciKaydi;
    private javax.swing.JButton btn_OtoparkBilgisi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
